apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javawebappsample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebappsample
    spec:
      containers:
      - name: javawebappsample
        image: tofascrtest.azurecr.io/javawebappsample:latest
        ports:
        - containerPort: 8080
